name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t sofusonfire/apitesting:latest -f WoooooooDockerrr/Dockerfile
    - name: Push Image to DockerHub
      run: |
       docker login -u sofusonfire -p ${{ secrets.DOCKER_TOKEN }}
       docker push sofusonfire/apitesting:latest